/**
 * Writes docs/io-list.md from shared/channels.ts, so the documented IO list
 * can never disagree with the one the software uses.
 *
 *   npm run docs:io-list
 */
import { writeFileSync } from 'node:fs';
import { CHANNELS, SYSTEM_INFO } from '../shared/channels';
import { SYSTEM_NAMES, type ChannelDef } from '../shared/types';

function limits(c: ChannelDef): string {
  const rule = c.alarm;
  if (!rule) return '';
  if (rule.type === 'state') return `${rule.severity} when 1`;
  const op = rule.type === 'low' ? '≤' : rule.type === 'abs' ? '\\|x\\| ≥' : '≥';
  return [
    rule.warning !== undefined ? `W ${op} ${rule.warning}` : '',
    rule.critical !== undefined ? `C ${op} ${rule.critical}` : '',
  ].filter(Boolean).join(', ');
}

const lines: string[] = [
  '# IO list',
  '',
  '<!-- Generated by `npm run docs:io-list` from shared/channels.ts. Do not edit by hand. -->',
  '',
  `${CHANNELS.length} monitored points. W = warning limit, C = critical limit. ` +
    'Points marked "blocked by" have their alarms suppressed while that machine is stopped.',
  '',
];

for (const system of SYSTEM_NAMES) {
  const channels = CHANNELS.filter((c) => c.system === system);
  lines.push(`## ${system}`, '', SYSTEM_INFO[system].summary, '');
  lines.push('| Tag | Point | Range | Unit | Alarm limits | Source | Address | Why it is monitored |');
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const c of channels) {
    const range = c.kind === 'digital' ? '0/1' : `${c.min} … ${c.max}`;
    const alarm = [limits(c), c.inhibitedBy ? `blocked by ${c.inhibitedBy}` : ''].filter(Boolean).join('; ');
    lines.push(`| \`${c.tag}\` | ${c.label} | ${range} | ${c.unit} | ${alarm} | ${c.source} | ${c.address} | ${c.description} |`);
  }
  lines.push('');
}

writeFileSync(new URL('../docs/io-list.md', import.meta.url), lines.join('\n'));
console.log(`docs/io-list.md: ${CHANNELS.length} points`);
